export let exampleTexts = new Map([
  [
    "hunchback",
    {
      lang: "fr",
      title: "The Hunchback of Notre-Dame",
      body: [
        "Il y a aujourd’hui trois cent quarante-huit ans six mois et dix-neuf jours que les Parisiens s’éveillèrent au bruit de toutes les cloches sonnant à grande volée dans la triple enceinte de la Cité, de l’Université et de la Ville. Ce n’est cependant pas un jour dont l’histoire ait gardé souvenir que le 6 janvier 1482. Rien de notable dans l’événement qui mettait ainsi en branle, dès le matin, les cloches et les bourgeois de Paris. Ce n’était ni un assaut de Picards ou de Bourguignons, ni une châsse menée en procession, ni une révolte d’écoliers dans la vigne de",
        "Laas, ni une entrée de notredit très redouté seigneur monsieur le roi, ni même une belle pendaison de larrons et de larronnesses à la Justice de Paris. Ce n’était pas non plus la survenue, si fréquente au quinzième siècle, de quelque ambassade chamarrée et empanachée. Il y avait à peine deux jours que la dernière cavalcade de ce genre, celle des ambassadeurs flamands chargés de conclure le mariage entre le dauphin et Marguerite de Flandre, avait fait son entrée à Paris, au grand ennui de M. e cardinal de Bourbon, qui, pour plaire au roi, avait dû faire bonne mine à toute cette rustique cohue de bourgmestres flamands,",
        "l et les régaler, en son hôtel de Bourbon, d’une moult belle moralité, sotie et farce, tandis qu’une pluie battante inondait à sa porte ses magnifiques tapisseries. Le 6 janvier, ce qui mettoit en émotion tout le populaire de Paris, comme dit Jehan de Troyes, c’était la double solennité, réunie depuis un temps immémorial, du jour des Rois et de la Fête des Fous. Ce jour-là, il devait y avoir feu de joie à la Grève, plantation de mai à la chapelle de Braque et mystère au Palais de Justice.",
        "  Le cri en avait été fait la veille à son de trompe dans les carrefours, par les gens de M. le prévôt, en beaux hoquetons de camelot violet, avec de grandes croix blanches sur la poitrine. La foule des bourgeois et des bourgeoises s’acheminait donc de toutes parts dès le matin, maisons et boutiques fermées, vers l’un des trois endroits désignés. Chacun avait pris parti, qui pour le feu de joie, qui pour le mai, qui pour le mystère. Il faut dire, à l’éloge de l’antique bon sens des badauds de Paris, que la plus grande partie de cette",
        "foule se dirigeait vers le feu de joie, l equel était tout à fait de saison, ou vers le mystère, qui devait être représenté dans la grand-salle du Palais bien couverte et bien close, et que les curieux s’accordaient à laisser le pauvre mai mal fleuri grelotter tout seul sous le ciel de janvier dans le cimetière de la chapelle de Braque. Le peuple affluait surtout dans les avenues du Palais de Justice, parce qu’on savait que les ambassadeurs flamands, arrivés de la surveille, se proposaient d’assister à la représentation du mystère et à l’élection du pape des fous, laquelle devait se faire également dans la grand-salle.",
      ],
    },
  ],

  [
    "london-bridge",
    {
      lang: "en",
      title: "London Bridge",
      body: [
        "London Bridge is falling down Falling down, falling down London Bridge is falling down My fair lady",
      ],
    },
  ],

  [
    "don-quijote",
    {
      lang: "sp",
      title: "Don Quijote",
      body: [
        "En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho tiempo que vivía un hidalgo de los de lanza en astillero, adarga antigua, rocín flaco y galgo corredor. Una olla de algo más vaca que carnero, salpicón las más noches, duelos y quebrantos los sábados, lantejas los viernes, algún palomino de añadidura los domingos, consumían las tres partes de su hacienda. El resto della concluían sayo de velarte, calzas de velludo para las fiestas, con sus pantuflos de lo mesmo, y los días de entresemana se honraba con su vellorí de lo más fino.",
        "Tenía en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza, que así ensillaba el rocín como tomaba la podadera. Frisaba la edad de nuestro hidalgo con los cincuenta años; era de complexión recia, seco de carnes, enjuto de rostro, gran madrugador y amigo de la caza. Quieren decir que tenía el sobrenombre de Quijada, o Quesada, que en esto hay alguna diferencia en los autores que deste caso escriben; aunque, por conjeturas verosímiles, se deja entender que se llamaba Quejana. Pero esto importa poco a nuestro cuento; basta que en la narración dél no se salga un punto de la verdad.",
        "Es, pues, de saber que este sobredicho hidalgo, los ratos que estaba ocioso, que eran los más del año, se daba a leer libros de caballerías, con tanta afición y gusto, que olvidó casi de todo punto el ejercicio de la caza, y aun la administración de su hacienda. Y llegó a tanto su curiosidad y desatino en esto, que vendió muchas hanegas de tierra de sembradura para comprar libros de caballerías en que leer, y así, llevó a su casa todos cuantos pudo haber dellos; y de todos, ningunos le parecían tan bien como los que compuso el famoso ",
        "Feliciano de Silva, porque la claridad de su prosa y aquellas entricadas razones suyas le parecían de perlas, y más cuando llegaba a leer aquellos requiebros y cartas de desafíos, donde en muchas partes hallaba escrito: La razón de la sinrazón que a mi razón se hace, de tal manera mi razón enflaquece, que con razón me quejo de la vuestra fermosura. Y también cuando leía: ...los altos cielos que de vuestra divinidad divinamente con las estrellas os fortifican, y os hacen merecedora del merecimiento que merece la vuestra grandeza.",
        "Con estas razones perdía el pobre caballero el juicio, y desvelábase por entenderlas y desentrañarles el sentido, que no se lo sacara ni las entendiera el mesmo Aristóteles, si resucitara para sólo ello. No estaba muy bien con las heridas que don Belianís daba y recebía, porque se imaginaba que, por grandes maestros que le hubiesen curado, no dejaría de tener el rostro y todo el cuerpo lleno de cicatrices y señales. Pero, con todo, alababa en su autor aquel acabar su libro con la promesa de aquella inacabable aventura, y muchas veces le vino deseo de tomar la pluma y dalle fin al pie de la letra, como allí se promete; ",
      ],
    },
  ],
  [
    "lorem-ipusm",
    {
      lang: "la",
      title: "Lorem ipsum",
      body: [
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa molestiae deserunt neque autem odio fugiat minus architecto sit ratione error totam cumque, obcaecati adipisci possimus iste voluptas cupiditate doloremque eveniet mollitia sint aperiam, aspernatur velit! Magni veniam doloremque nihil est consectetur accusantium numquam? Minima dolorum harum accusamus ut reprehenderit inventore in consectetur hic optio eum officiis voluptates repellat deleniti, ipsa non porro tempore? Quidem ipsam quas sed ducimus totam minus quae tenetur officiis possimus! Autem delectus minus maxime quae saepe accusamus iure, nisi iste a iusto? Sunt quibusdam consectetur doloremque minus quos voluptates quae cum eius, unde reiciendis quam recusandae reprehenderit commodi sequi ex consequuntur modi distinctio.",
        "Quas id modi veniam, dolores assumenda suscipit quos error unde distinctio quam facere repellendus obcaecati, eligendi aliquam architecto ullam sequi provident minima nostrum accusamus earum officia! Officia velit quasi veniam a totam, autem, ullam expedita quae eligendi nihil atque beatae fugiat qui in tenetur sequi debitis deleniti magnam cupiditate sapiente quam unde? Dolor, est! Temporibus, incidunt illum nesciunt voluptas vel odit molestias, consectetur velit cum consequatur placeat aliquid optio, harum recusandae soluta est distinctio. Aperiam, error. Quam non at harum. Quae, magnam? Eius iste aperiam mollitia esse officia sequi id! Reiciendis culpa dolor iste cumque harum adipisci maxime!",
        "Possimus, architecto neque doloremque pariatur delectus recusandae sed at autem quo vero sint officiis, enim, aliquid beatae! Vitae dolorem praesentium asperiores harum quas, corrupti ipsa deleniti tenetur amet odio ipsam, quasi quis quae. Inventore velit optio porro provident, doloremque nesciunt? Nam numquam porro aspernatur optio ea facilis eum expedita, distinctio fugit eligendi deleniti illum voluptatum reiciendis pariatur, atque nemo minima velit dolores veritatis incidunt suscipit, dolore ullam libero reprehenderit. Nihil illum cumque vel ex quod distinctio corporis, pariatur iusto modi quisquam quo itaque consequuntur voluptas esse laudantium voluptatibus commodi voluptatum temporibus voluptates.",
        "Consequuntur cupiditate dolorem blanditiis porro sapiente sequi tempore praesentium. Dicta laborum similique magni labore, distinctio reprehenderit pariatur magnam! Nisi, eos porro! Natus, exercitationem tenetur praesentium sapiente incidunt quis architecto recusandae debitis dolore eligendi quae, non corporis, quisquam fugit voluptatem quam vel. Quisquam facere nihil, sit esse perferendis omnis consectetur amet soluta natus, velit, culpa placeat nam laborum totam eos. Deleniti sapiente laborum ratione, quo a tempora ipsa optio, iusto, saepe eligendi voluptatibus vero in vel repudiandae fugiat facilis inventore provident vitae veritatis pariatur non totam explicabo tempore? Sed facilis est suscipit voluptatum dolorem itaque?",
        "Amet commodi dolorem similique officia illo a itaque recusandae iure aliquam impedit nesciunt iusto, perspiciatis totam perferendis et autem ipsa, repellendus aut rerum dolores vero. Voluptate incidunt dolore accusamus laborum placeat fugit omnis, vitae mollitia reiciendis, ipsum quas, molestias assumenda commodi veritatis consequuntur. Cum quasi consequatur praesentium corrupti eius error laudantium, ipsum eligendi doloremque. Veritatis modi magni totam eum nobis repudiandae accusamus ratione sed sapiente rem qui eaque aliquid quasi a similique nihil, ipsum amet earum praesentium. Mollitia facilis iusto atque, ab cum ducimus repellat a veritatis accusamus iure nihil sint consequatur in pariatur repellendus earum, esse natus? Voluptates sit tenetur voluptatem voluptate praesentium veniam autem ipsum amet unde!",
      ],
    },
  ],

  [
    "hänsel-und-grethel",
    {
      lang: "de",
      title: "Hänsel und Grethel",
      body: [
        "Vor einem großen Walde wohnte ein armer Holzhacker mit seiner Frau und seinen zwei Kindern; das Bübchen hieß Hänsel und das Mädchen Grethel. Er hatte wenig zu beißen und zu brechen, und einmal, als große Theuerung ins Land kam, konnte er auch das täglich Brot nicht mehr schaffen. Wie er sich nun Abends im Bette Gedanken machte und sich vor Sorgen herum wälzte, seufzte er und sprach zu seiner Frau „was soll aus uns werden? wie können wir unsere armen Kinder ernähren, da wir für uns selbst nichts mehr haben?“ „Weißt du was, Mann,“ antwortete die ",
        "Frau, „wir wollen Morgen in aller Frühe die Kinder hinaus in den Wald führen, wo er am dicksten ist: da machen wir ihnen ein Feuer an und geben jedem noch ein Stückchen Brot, dann gehen wir an unsere Arbeit und lassen sie allein. Sie finden den Weg nicht wieder nach Haus und wir sind sie los.“ „Nein, Frau,“ sagte der Mann, „das thue ich nicht; wie sollt ichs übers Herz bringen meine Kinder im Walde allein zu lassen, die wilden Thiere würden bald kommen und sie zerreißen.“ „O du Narr,“ sagte sie, „dann müssen wir alle viere Hungers sterben, du kannst nur die Bretter für die Särge hobelen,“ und ließ ihm keine Ruhe bis er einwilligte. „Aber die armen Kinder dauern mich doch“ sagte der Mann.",
        "Die zwei Kinder hatten vor Hunger auch nicht einschlafen können und hatten gehört was die Stiefmutter zum Vater gesagt hatte. Grethel weinte bittere Thränen und sprach zu Hänsel „nun ists um uns geschehen.“ „Still, Grethel,“ sprach Hänsel, „gräme dich nicht, ich will uns schon helfen.“ Und als die Alten eingeschlafen waren, stand er auf, zog sein Röcklein an, machte die Unterthüre auf und schlich sich hinaus. Da schien der Mond ganz helle, und die weißen Kieselsteine, die vor dem Haus lagen, glänzten wie lauter Batzen. Hänsel bückte sich und steckte so viel in sein Rocktäschlein, als nur hinein wollten.",
        " Dann gieng er wieder zurück, sprach zu Grethel „sei getrost, liebes Schwesterchen und schlaf nur ruhig ein, Gott wird uns nicht verlassen,“ und legte sich wieder in sein Bett. Als der Tag anbrach, noch ehe die Sonne aufgegangen war, kam schon die Frau und weckte die beiden Kinder, „steht auf, ihr Faullenzer, wir wollen in den Wald gehen und Holz holen.“ Dann gab sie jedem ein Stückchen Brot und sprach „da habt ihr etwas für den Mittag, aber eßts nicht vorher auf, weiter kriegt ihr nichts.“ Grethel nahm das Brot unter die Schürze, weil Hänsel die Steine in der Tasche hatte.",
        " Danach machten sie sich alle zusammen auf den Weg nach dem Wald. Als sie ein Weilchen gegangen waren, stand Hänsel still und guckte nach dem Haus zurück und that das wieder und immer wieder. Der Vater sprach „Hänsel, was guckst du da und bleibst zurück, hab Acht und vergiß deine Beine nicht.“ „Ach, Vater,“ sagte Hänsel, „ich sehe nach meinem weißen Kätzchen, das sitzt oben auf dem Dach und will mir Ade sagen.“ Die Frau sprach „Narr, das ist dein Kätzchen nicht, das ist die Morgensonne, die auf den Schornstein scheint.“ ",
        "Hänsel aber hatte nicht nach dem Kätzchen gesehen, sondern immer einen von den blanken Kieselsteinen aus seiner Tasche auf den Weg geworfen. Als sie mitten in den Wald gekommen waren, sprach der Vater „nun sammelt Holz, ihr Kinder, ich will ein Feuer anmachen, damit ihr nicht friert.“ Hänsel und Grethel trugen Reisig zusammen, einen kleinen Berg hoch. Das Reisig ward angezündet, und als die Flamme recht hoch brannte, sagte die Frau „nun legt euch ans Feuer, ihr Kinder und ruht euch aus, wir gehen in den Wald und hauen Holz. Wenn wir fertig sind, kommen wir wieder und holen euch ab.“",
      ],
    },
  ],
])

export let langOptions = new Map([
  ["enfr", "en-fr"],
  ["fren", "fr-en"],
  ["deen", "de-en"],
  ["spen", "sp-en"],
])

export let diffWordColors = `data-[diff=hard]:bg-orange-800 data-[diff=med]:bg-yellow-800 data-[diff=easy]:bg-green-800 data-[diff=wk]:bg-neutral-900 bg-purple-800`

export let diffBtnColors = {
  hard: "data-[state=on]:bg-orange-800 hover:bg-orange-800",
  med: "data-[state=on]:bg-yellow-800 hover:bg-yellow-800",
  easy: "data-[state=on]:bg-green-800 hover:bg-green-800",
  wk: "",
  null: "data-[state=on]:bg-purple-800 hover:bg-purple-800",
}

export const exampleData = [
  ["lorem", { word: "Lorem", diff: "wk", lang: "la" }],
  ["ipsum", { word: "ipsum", diff: "wk", lang: "la" }],
  ["dolor", { word: "dolor", diff: "wk", lang: "la" }],
  ["sit", { word: "sit", diff: "wk", lang: "la" }],
  ["amet", { word: "amet", diff: "hard", lang: "la" }],
  ["consectetur", { word: "consectetur", diff: "wk", lang: "la" }],
  ["adipisicing", { word: "adipisicing", diff: "wk", lang: "la" }],
  ["elit", { word: "elit", diff: "wk", lang: "la" }],
  ["culpa", { word: "Culpa", diff: "wk", lang: "la" }],
  ["molestiae", { word: "molestiae", diff: "wk", lang: "la" }],
  ["deserunt", { word: "deserunt", diff: "wk", lang: "la" }],
  ["neque", { word: "neque", diff: "wk", lang: "la" }],
  ["autem", { word: "autem", diff: "wk", lang: "la" }],
  ["odio", { word: "odio", diff: "wk", lang: "la" }],
  ["fugiat", { word: "fugiat", diff: "wk", lang: "la" }],
  ["minus", { word: "minus", diff: "wk", lang: "la" }],
  ["architecto", { word: "architecto", diff: "wk", lang: "la" }],
  ["ratione", { word: "ratione", diff: "wk", lang: "la" }],
  ["error", { word: "error", diff: "wk", lang: "la" }],
  ["totam", { word: "totam", diff: "wk", lang: "la" }],
  ["obcaecati", { word: "obcaecati", diff: "wk", lang: "la" }],
  ["adipisci", { word: "adipisci", diff: "wk", lang: "la" }],
  ["possimus", { word: "possimus", diff: "wk", lang: "la" }],
  ["iste", { word: "iste", diff: "wk", lang: "la" }],
  ["voluptas", { word: "voluptas", diff: "wk", lang: "la" }],
  ["cupiditate", { word: "cupiditate", diff: "wk", lang: "la" }],
  ["doloremque", { word: "doloremque", diff: "wk", lang: "la" }],
  ["eveniet", { word: "eveniet", diff: "wk", lang: "la" }],
  ["mollitia", { word: "mollitia", diff: "hard", lang: "la" }],
  ["sint", { word: "sint", diff: "wk", lang: "la" }],
  ["aperiam", { word: "aperiam", diff: "hard", lang: "la" }],
  ["aspernatur", { word: "aspernatur", diff: "easy", lang: "la" }],
  ["velit", { word: "velit", diff: "wk", lang: "la" }],
  ["magni", { word: "Magni", diff: "wk", lang: "la" }],
  ["veniam", { word: "veniam", diff: "wk", lang: "la" }],
  ["nihil", { word: "nihil", diff: "hard", lang: "la" }],
  ["est", { word: "est", diff: "med", lang: "la" }],
  ["accusantium", { word: "accusantium", diff: "wk", lang: "la" }],
  ["numquam", { word: "numquam", diff: "wk", lang: "la" }],
  ["minima", { word: "Minima", diff: "wk", lang: "la" }],
  ["dolorum", { word: "dolorum", diff: "wk", lang: "la" }],
  ["harum", { word: "harum", diff: "wk", lang: "la" }],
  ["accusamus", { word: "accusamus", diff: "wk", lang: "la" }],
  ["ut", { word: "ut", diff: "easy", lang: "la" }],
  ["reprehenderit", { word: "reprehenderit", diff: "wk", lang: "la" }],
  ["inventore", { word: "inventore", diff: "wk", lang: "la" }],
  ["hic", { word: "hic", diff: "easy", lang: "la" }],
  ["optio", { word: "optio", diff: "wk", lang: "la" }],
  ["eum", { word: "eum", diff: "med", lang: "la" }],
  ["officiis", { word: "officiis", diff: "wk", lang: "la" }],
  ["voluptates", { word: "voluptates", diff: "wk", lang: "la" }],
  ["repellat", { word: "repellat", diff: "med", lang: "la" }],
  ["deleniti", { word: "deleniti", diff: "wk", lang: "la" }],
  ["ipsa", { word: "ipsa", diff: "hard", lang: "la" }],
  ["porro", { word: "porro", diff: "easy", lang: "la" }],
  ["tempore", { word: "tempore", diff: "easy", lang: "la" }],
  ["quidem", { word: "Quidem", diff: "easy", lang: "la" }],
  ["ipsam", { word: "ipsam", diff: "wk", lang: "la" }],
  ["quas", { word: "quas", diff: "wk", lang: "la" }],
  ["sed", { word: "sed", diff: "wk", lang: "la" }],
  ["ducimus", { word: "ducimus", diff: "med", lang: "la" }],
  ["quae", { word: "quae", diff: "med", lang: "la" }],
  ["tenetur", { word: "tenetur", diff: "med", lang: "la" }],
  ["delectus", { word: "delectus", diff: "med", lang: "la" }],
  ["maxime", { word: "maxime", diff: "easy", lang: "la" }],
  ["saepe", { word: "saepe", diff: "easy", lang: "la" }],
  ["iure", { word: "iure", diff: "wk", lang: "la" }],
  ["nisi", { word: "nisi", diff: "hard", lang: "la" }],
  ["iusto", { word: "iusto", diff: "wk", lang: "la" }],
  ["quibusdam", { word: "quibusdam", diff: "wk", lang: "la" }],
  ["sunt", { word: "Sunt", diff: "wk", lang: "la" }],
  ["quos", { word: "quos", diff: "wk", lang: "la" }],
  ["cum", { word: "cum", diff: "easy", lang: "la" }],
  ["eius", { word: "eius", diff: "wk", lang: "la" }],
  ["unde", { word: "unde", diff: "wk", lang: "la" }],
  ["reiciendis", { word: "reiciendis", diff: "hard", lang: "la" }],
  ["quam", { word: "quam", diff: "hard", lang: "la" }],
  ["recusandae", { word: "recusandae", diff: "easy", lang: "la" }],
  ["commodi", { word: "commodi", diff: "med", lang: "la" }],
  ["sequi", { word: "sequi", diff: "wk", lang: "la" }],
  ["ex", { word: "ex", diff: "wk", lang: "la" }],
  ["consequuntur", { word: "consequuntur", diff: "wk", lang: "la" }],
  ["modi", { word: "modi", diff: "wk", lang: "la" }],
  ["distinctio", { word: "distinctio", diff: "hard", lang: "la" }],
  ["cumque", { word: "cumque", diff: "wk", lang: "la" }],
]
